### ISSUE TITLE
Need to encode parameters in api call

### ISSUE THREAD

**Issue by michaelgrifalconi** [grisu48/openqa-jobs#2]
Hello Felix!

I found a small issue with the tool, I cannot query for the test `mau-webserver+15`.

After a brief investigation, I found that `mau-webserver%2B15` works as expected.
I guess the api call should be url-encoded to prevent such issues.

**Comment by grisu48** [comment]
Thanks for reporting, I'll have a look on Monday! Wish you a nice weekend in the meantime :beers:

**Comment by grisu48** [comment]
Fixed in https://github.com/grisu48/openqa-jobs/pull/3. Thanks for the report :+1:
